# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(784, 619)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.table_widget = QtWidgets.QTableWidget(Form)
        self.table_widget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.gridLayout.addWidget(self.table_widget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(Form)
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_clean = QtWidgets.QPushButton(Form)
        self.button_clean.setObjectName("button_clean")
        self.horizontalLayout.addWidget(self.button_clean)
        self.button_save = QtWidgets.QPushButton(Form)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.words_edit = QtWidgets.QLineEdit(Form)
        self.words_edit.setObjectName("words_edit")
        self.horizontalLayout_2.addWidget(self.words_edit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.chars_edit = QtWidgets.QLineEdit(Form)
        self.chars_edit.setObjectName("chars_edit")
        self.horizontalLayout_2.addWidget(self.chars_edit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_open.setText(_translate("Form", "Abrir planilha"))
        self.button_clean.setText(_translate("Form", "Limpar coluna(s) selecionada(s)"))
        self.button_save.setText(_translate("Form", "Salvar planilha"))
        self.label.setText(_translate("Form", "Remover palavras"))
        self.label_2.setText(_translate("Form", "Remover caracteres"))
